#
# minimal pgDog configuration for a single user, single
# primary database running on the same host.
#
[general]
host = "0.0.0.0"
port = 6432
shutdown_timeout = 5_000

[[databases]]
name = "pgdog"
host = "127.0.0.1"

[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_0"
shard = 0

[[databases]]
name = "pgdog_sharded"
host = "127.0.0.1"
database_name = "shard_1"
shard = 1

[[plugins]]
name = "pgdog_routing"

[admin]
password = "pgdog"
